# Generated by Django 3.2.9 on 2021-11-07 22:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogCitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='historial',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=tinymce.models.HTMLField(),
        ),
    ]
