# Generated by Django 3.2.6 on 2021-11-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogCitas', '0003_horariostrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
